import { useEffect } from 'react'
import { company } from '@/config/company'

export type SeoProps = {
  /** Page title without the brand suffix. */
  title: string
  description: string
  /** Route path beginning with "/" — used for the canonical URL. */
  path: string
  /** Absolute or root-relative OG image path. */
  ogImage?: string
  noindex?: boolean
  jsonLd?: Record<string, unknown> | Record<string, unknown>[]
}

// Social platforms do not accept SVG — this PNG is generated by `npm run assets`.
const DEFAULT_OG_IMAGE = '/og-image.png'
const JSON_LD_ID = 'chenduraa-jsonld'

export function fullTitle(title: string): string {
  return title.includes(company.shortName) || title.includes('Chenduraa')
    ? title
    : `${title} | ${company.legalName}`
}

export function canonicalUrl(path: string): string {
  const clean = path === '/' ? '/' : `/${path.replace(/^\/+|\/+$/g, '')}`
  return `${company.siteUrl}${clean}`
}

/* ----------------------------- SSR collection ----------------------------- */

let collected: SeoProps | null = null

/** @internal used by entry-server during prerendering */
export function resetCollectedSeo(): void {
  collected = null
}

/** @internal used by entry-server during prerendering */
export function getCollectedSeo(): SeoProps | null {
  return collected
}

/* -------------------------------- component ------------------------------- */

/**
 * Declares page metadata. During the build it is collected and written into the
 * static HTML head; in the browser it updates the document on route changes.
 */
export function Seo(props: SeoProps): null {
  if (typeof document === 'undefined') {
    collected = props
  }

  const { title, description, path, ogImage, noindex, jsonLd } = props

  useEffect(() => {
    const resolvedTitle = fullTitle(title)
    const canonical = canonicalUrl(path)
    const image = `${company.siteUrl}${ogImage ?? DEFAULT_OG_IMAGE}`

    document.title = resolvedTitle
    setMeta('name', 'description', description)
    setMeta('name', 'robots', noindex ? 'noindex, nofollow' : 'index, follow')
    setLink('canonical', canonical)

    setMeta('property', 'og:type', 'website')
    setMeta('property', 'og:site_name', company.legalName)
    setMeta('property', 'og:title', resolvedTitle)
    setMeta('property', 'og:description', description)
    setMeta('property', 'og:url', canonical)
    setMeta('property', 'og:image', image)
    setMeta('property', 'og:locale', 'en_IN')

    setMeta('name', 'twitter:card', 'summary_large_image')
    setMeta('name', 'twitter:title', resolvedTitle)
    setMeta('name', 'twitter:description', description)
    setMeta('name', 'twitter:image', image)

    const existing = document.getElementById(JSON_LD_ID)
    existing?.remove()
    if (jsonLd) {
      const script = document.createElement('script')
      script.type = 'application/ld+json'
      script.id = JSON_LD_ID
      script.textContent = JSON.stringify(jsonLd)
      document.head.appendChild(script)
    }
  }, [title, description, path, ogImage, noindex, jsonLd])

  return null
}

function setMeta(attr: 'name' | 'property', key: string, content: string): void {
  let tag = document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${key}"]`)
  if (!tag) {
    tag = document.createElement('meta')
    tag.setAttribute(attr, key)
    document.head.appendChild(tag)
  }
  tag.content = content
}

function setLink(rel: string, href: string): void {
  let tag = document.head.querySelector<HTMLLinkElement>(`link[rel="${rel}"]`)
  if (!tag) {
    tag = document.createElement('link')
    tag.rel = rel
    document.head.appendChild(tag)
  }
  tag.href = href
}

/* ------------------------------ head as HTML ------------------------------ */

function escapeAttr(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Renders collected metadata as head HTML for the prerendered page. */
export function seoToHtml(seo: SeoProps): string {
  const resolvedTitle = fullTitle(seo.title)
  const canonical = canonicalUrl(seo.path)
  const image = `${company.siteUrl}${seo.ogImage ?? DEFAULT_OG_IMAGE}`

  const tags = [
    `<title>${escapeAttr(resolvedTitle)}</title>`,
    meta('name', 'description', seo.description),
    meta('name', 'robots', seo.noindex ? 'noindex, nofollow' : 'index, follow'),
    `<link rel="canonical" href="${escapeAttr(canonical)}" />`,
    meta('property', 'og:type', 'website'),
    meta('property', 'og:site_name', company.legalName),
    meta('property', 'og:title', resolvedTitle),
    meta('property', 'og:description', seo.description),
    meta('property', 'og:url', canonical),
    meta('property', 'og:image', image),
    meta('property', 'og:locale', 'en_IN'),
    meta('name', 'twitter:card', 'summary_large_image'),
    meta('name', 'twitter:title', resolvedTitle),
    meta('name', 'twitter:description', seo.description),
    meta('name', 'twitter:image', image),
  ]

  if (seo.jsonLd) {
    const json = JSON.stringify(seo.jsonLd).replace(/</g, '\\u003c')
    tags.push(`<script type="application/ld+json" id="${JSON_LD_ID}">${json}</script>`)
  }

  return tags.join('\n    ')
}

function meta(attr: 'name' | 'property', key: string, content: string): string {
  return `<meta ${attr}="${key}" content="${escapeAttr(content)}" />`
}
